name: A workflow for my new Hello World file
on: push
jobs:
  build:
    name: New Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Sabrina"
